require_relative '../node_modules/react-native-macos/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :macos, '10.15'

target 'RNLocalizeExample' do
  use_native_modules!

  use_react_native!(
    :path => '../node_modules/react-native-macos',
    # to enable hermes on macOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Pods specifically for macOS target

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
